### ISSUE TITLE
[chat example] "npm run dev" does not work

### ISSUE THREAD

**Issue by mherodev** [yahoo/fluxible#345]
You can see from the following example that something is setup incorrectly. 

The examples-level package.json includes nodemon, so it should be able to be found if those dependencies are inherited correctly. Installing nodemon  again at the chat-level simply goes down a rabbit hole of missing dependencies and errors. Coping those dependencies up from example to chat and installing results in another error. Not quite sure what's expected, but as mentioned, the following is what occurs on Ubuntu 14.04:

$ git clone https://github.com/yahoo/fluxible.git
$ cd fluxible/examples/
$ npm install
$ cd chat
$ npm run dev

> flux-example-chat@0.0.0 dev /home/mherold/git/fluxible/examples/chat
> node webpack-dev-server.js & PORT=3001 nodemon server.js -e js,jsx

sh: 1: nodemon: not found

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! flux-example-chat@0.0.0 dev: `node webpack-dev-server.js & PORT=3001 nodemon server.js -e js,jsx`
npm ERR! spawn ENOENT

**Comment by mridgway** [comment]
You need to run `npm install` from the examples directory or from the root (which also does installs for all subfolders) and then it should work to run `npm run dev` from the chat folder.

**Comment by mridgway** [comment]
Seems to be a difference in latest node: it doesn't look in parent directory's `.bin` folder for binaries like node v0.10.x did. I will look more into this.

**Comment by mherodev** [comment]
Thanks for looking into this so quickly!

**Comment by mridgway** [comment]
Turns out I had nodemon installed globally in my node v0.10.x folder but not others. I have pushed a fix that will use nodemon directly from the parent node_modules folder instead.

**Comment by mherodev** [comment]
So close, Michael; it seems like there are a couple issues:

1) react-router and history have some weird versioning issues; I've seen this in other projects post v3 update which changed how peer dependencies work.

2) The following error, might be a symptom of above:

$ npm run dev

> flux-example-chat@0.0.0 dev /home/mherold/git/fluxible/examples/chat
> node webpack-dev-server.js & PORT=3001 ../node_modules/.bin/nodemon server.js -e js,jsx

[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1238:14)
    at listen (net.js:1274:10)
    at Server.listen (net.js:1370:5)
    at Server.listen (/home/mherold/git/fluxible/examples/node_modules/webpack-dev-server/lib/Server.js:269:27)
    at Object.<anonymous> (/home/mherold/git/fluxible/examples/chat/webpack-dev-server.js:13:4)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
Listening on port 3001

**Comment by mherodev** [comment]
Including history in the project.json will resolve the peer dependency, but the second issue still occurs.

pre-change, npm uninstall, install history@1.13.x and then install react-router:
├── history@1.13.1  extraneous
└── react-router@1.0.2

**Comment by mridgway** [comment]
We have not upgraded the react-router example to react-router@1.x yet, so I'm not sure what it's in the package.json for `/examples`. Right now, the react-router examples needs an extra `npm install` from within the `/examples/react-router` folder because it uses React 0.13 as well.

The `EADDRINUSE` error is probably because the original command failed but the webpack dev server did not exit correctly. Try running `ps aux | grep webpack-dev-server` and kill the process that is running.

**Comment by mherodev** [comment]
You were correct! Sadly, I am determined to run into more issues...

I cannot submit a message to any threads, or view any thread outside of the default thread. Clicking on a thread gives me the following response:

TypeError: Cannot read property 'id' of undefined
   at action (/home/mherold/git/fluxible/examples/chat/configs/routes.js:16:42)
   at Immediate._onImmediate (/home/mherold/git/fluxible/examples/node_modules/fluxible/lib/FluxibleContext.js:94:34)
   at processImmediate [as _immediateCallback] (timers.js:384:17)

And here's the console log, for reference:

$ npm run dev

> flux-example-chat@0.0.0 dev /home/mherold/git/fluxible/examples/chat
> node webpack-dev-server.js & PORT=3001 ../node_modules/.bin/nodemon server.js -e js,jsx

[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
Webpack Dev Server listening on port 3000
Listening on port 3001
TypeError: Cannot read property 'id' of undefined
    at action (/home/mherold/git/fluxible/examples/chat/configs/routes.js:16:42)
    at Immediate._onImmediate (/home/mherold/git/fluxible/examples/node_modules/fluxible/lib/FluxibleContext.js:94:34)
    at processImmediate [as _immediateCallback] (timers.js:384:17)

Would I be better off reverting to earlier versions of npm or node to run this example code?

**Comment by mridgway** [comment]
My apologies for the hiccups. If you go into the `examples` directory and run `npm i fluxible-router@0.4.x` it should run correctly. I am updating the package.json to fix the version of `fluxible-router`.

**Comment by mherodev** [comment]
Fantastic, I was able to run the example!
